name: sakr-queue

services:
  bot:
    container_name: sakr-queue-bot
    image: '${IMAGE_NAME:-ghcr.io/d1xer228/queue-sakr-bot}'
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
