name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  packages: write
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Build and Publish Tag Docker image
      uses: DrSkunk/gp-docker-action@1.1.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: my-cool-service
